permalink: pretty

collections:
  cs:
    output: true
  ds:
    output: true
  ml:
    output: true
  posts:
    output: true

defaults:
  - scope:
      type: cs
    values:
      layout: project
  - scope:
      type: ds
    values:
      layout: project
  - scope:
      type: ml
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: "assets/img"
    values:
      image: true